In [2]:
import numpy as np

## PART A - Create a Notebook to demonstrate Numpy Operations

#### Question 1 -
Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [3]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

####Question 2
Create a new array of shape 3 with random numbers between 0 and 1.

In [12]:
new_arr = np.random.rand(3)
print(f"New array is {new_arr}")
print(f"The shape of new array is {new_arr.shape}")

New array is [0.39414351 0.22510609 0.39100484]
The shape of new array is (3,)


####Question 3
 Create a 2 D array [[10,20,45],[30,12,16],[42,17,56]] and perform the following operations:
Slice the 2D array to get the first two rows, and slice the 2D array to get the last two rows

In [33]:
arr = np.array([[10,20,45],[30,12,16],[42,17,56]])#
print("\nArray:")
print(arr)

slice_first_two_rows = arr[:2]
print("\nFirst two rows are:")
print(slice_first_two_rows)

slice_last_two_rows = arr[1:]
print("\nLast two rows are:")
print(slice_last_two_rows)


Array:
[[10 20 45]
 [30 12 16]
 [42 17 56]]

First two rows are:
[[10 20 45]
 [30 12 16]]

Last two rows are:
[[30 12 16]
 [42 17 56]]


####Question 4
Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally,
and split the arrays into smaller arrays.

In [31]:
arr1 = np.array([[10,20],[30,12]])
arr2 = np.array([[42,17],[56,16]])

arr3 = np.vstack((arr1,arr2))
print("\nVertical stack:")
print(arr3)

arr4 = np.hstack((arr1,arr2))
print("\nHorizontal stack:")
print(arr4)


Vertical stack:
[[10 20]
 [30 12]
 [42 17]
 [56 16]]

Horizontal stack:
[[10 20 42 17]
 [30 12 56 16]]


In [29]:
# flatten the array
flatten_arr = arr4.flatten()
print(f"Flatten array: {flatten_arr}")

# define the size of the subarray
n = 3

#split the arrays into subarrays
subarray = []
for i in range(0, len(flatten_arr), n):
  subarray.append(flatten_arr[i:i + n])
print(f"Subarray: {subarray}")

Flatten array: [10 20 42 17 30 12 56 16]
Subarray: [array([10, 20, 42]), array([17, 30, 12]), array([56, 16])]


####Question 5
Create two matrices 𝑋 = ([[5, 7, 2],[4, 5, 6],[7, 4 ,2]]), 𝑌 = ([[4, 2],[6, 2],[4, 2]]),
Is it possible to multiply these matrices?
Demonstrate the case when it is not possible to.

 ##### Answer -
 Is it possible to multiply these matrices?

  Yes, because X has three columns and Y has 3 rows, therefore they are compatible

##### Answer -

Demonstrate the case when it is not possible to.

In case where Z matrix = ([[4, 2],[6, 2]]). The Z and X matrices can not be multiplied. Z has 2 rows and X has 3 rows, therefore they are not compatible.

#### Question 6
 Create two arrays, 𝑥 = ([2, −1, −8]) 𝑦 = ([3, 1, −2]),

Find the Shape, Number of dimensions of vector x.

Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions
after reshaping y to a matrix of (3,1).

In [27]:
x = np.array([2, -1, -8])
print("Shape of x:", x.shape)
print("Number of dimensions of x:", x.ndim)
y = x.reshape(3,1)
print("\nOutput of y:")
print(y)
print(f"Shape of y: {y.shape}")
print(f"Number of dimensions of y: {y.ndim}")

Shape of x: (3,)
Number of dimensions of x: 1

Output of y:
[[ 2]
 [-1]
 [-8]]
Shape of y: (3, 1)
Number of dimensions of y: 2


####Question 7
 How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3
matrix.

In [36]:
# Create a 3x3 matrix
matrix = np.array([[5, 7, 2],
                   [4, 5, 6],
                   [7, 4, 2]])

# Create a 1x3 array
vector = np.array([1, 2, 3])

# Subtract the vector from the matrix
result_subtraction = matrix - vector

print("\nResult of Subtraction:")
print(result_subtraction)


# Multiply the matrix by the vector
result_multiplication = matrix * vector

print("\nResult of Multiplication:")
print(result_multiplication)



Result of Subtraction:
[[ 4  5 -1]
 [ 3  3  3]
 [ 6  2 -1]]

Result of Multiplication:
[[ 5 14  6]
 [ 4 10 18]
 [ 7  8  6]]


## PART B - Linear Equations

### Question B

Determine the singularity of the system of equations, comment on the expected solution of the system.
Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be
solved using NumPy functions.

#### Part B.1

1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

In [5]:
import numpy as np

# Coefficient matrix A
A = np.array([[4, 1, -2],
              [2, -3, 2],
              [1, 2, 3]])

# Calculate the determinant
det_A = np.linalg.det(A)

print(det_A)


-70.00000000000003


In [2]:
# Coefficient matrix A
A = np.array([[4, 1, -2],
              [2, -3, 2],
              [1, 2, 3]])

# Constants vector b
b = np.array([10, -4, 6])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A_inv by b to get the solution vector
solution = np.dot(A_inv, b)

# Output the solution
print(solution)


[ 1.8  2.4 -0.2]


The system of equations is non-singular because the det(A)= -70 and not zero. The system has exactly one unique solution, therefore the system can be solved using matrix inversion.

#### Part B.2

1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

In [4]:
# Coefficient matrix A
A = np.array([[2, -1, 3, 4],
              [4, -2, 6, 8],
              [3, 1, -2, 2],
              [1, 3, -4, 1]])

# Calculate the determinant
det_A = np.linalg.det(A)

print(det_A)


0.0


The system of equations is singular because the det(A)= 0. The system has no solution, therefore the system cannot be solved.

In [35]:
!git config --global user.name "Messiri4"
!git config --global user.email "messirimiracle.com"


In [47]:
!git clone https://github.com/Messiri4/Lab-1-Basic-NumPy-Operations


fatal: destination path 'Lab-1-Basic-NumPy-Operations' already exists and is not an empty directory.


In [49]:
%cd Lab-1-Basic-NumPy-Operations

/content/Lab-1-Basic-NumPy-Operations


In [56]:
%cd ..


/content


In [57]:
!ls

Lab-1-Basic-NumPy-Operations  sample_data


In [58]:
%cd sample_data/

/content/sample_data


In [59]:
!ls

anscombe.json		     california_housing_train.csv  mnist_train_small.csv
california_housing_test.csv  mnist_test.csv		   README.md


In [60]:
%cd ..

/content


In [61]:
%cd ..

/


In [62]:
!ls

bin			    datalab  lib     media		       proc	   sbin  tools
boot			    dev      lib32   mnt		       python-apt  srv	 usr
content			    etc      lib64   NGC-DL-CONTAINER-LICENSE  root	   sys	 var
cuda-keyring_1.0-1_all.deb  home     libx32  opt		       run	   tmp


In [54]:
!pwd


/content/Lab-1-Basic-NumPy-Operations


In [52]:
!mv Miracle_Messiri_9030337_Section2_Lab1.py /content/Lab-1-Basic-NumPy-Operations/


mv: cannot stat 'Miracle_Messiri_9030337_Section2_Lab1.ipynb': No such file or directory


In [ ]:
%cd your_repository
!git add .
!git commit -m "Initial commit"
